plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme
#remote_theme: pmarsceill/just-the-docs@v0.3.3
url: https://ucsb-cs24.github.io/s25 
baseurl: "/s25"  
instructor: "Diba Mirza"
name: "CS24 Spring 2025"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 S25"
github_url: https://github.com/ucsb-cs24/s25
qtr: "S25"
quarter: "Spring 2025"
lecture_times: "TR 12:30p - 1:45p"
lecture_location: "BUCHN 1940"
office_hours: "Thursdays 2p - 4p, HFH 1155"
lab_times: "F: 2p, 3p, 4p, 5p, and 6p"
tas: "Ally	Chu, Brenna	Scholte, Daniel	Lopez, Kali	Hale, Sarah	Hyatt"
ulas: "Cindy	Zhao, Nikhil	Kapasi, Olivia	Chen"
class_org:
   name: ucsb-cs24-s25
   url: https://github.com/ucsb-cs24-s25
   githublinker: CS24 S25
   
lect_repo: https://github.com/ucsb-cs24-s25/cs24-s25-lectures
start_week: 1
start_date: 2025-03-30
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2025-03-31" },
  {"label":"Drop deadline (no W grade)","date":"2025-10-25" },
  {"label":"Memorial Day - No lecture", "date":"2025-05-26" },
  {"label":"F25 Instruction Ends", "date":"2025-06-06" },  
  {"label":"Final Exam", "date":"2025-06-09" },  
  {"label":"F25 Quarter Ends", "date":"2025-06-13" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false

  pa:
    output: true
    permalink: /pa/:path/
    last_before: false

  lp:
    output: true
    permalink: /lp/:path/
    last_before: false
    
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: lp
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout

theme: jekyll-theme-cayman
